services:
  pqrs:
    build: ./pqrs
    container_name: fanpage-pqrs
    ports:
      - "8080:80"
    restart: unless-stopped

  nextcloud:
    build: ./nextcloud
    container_name: fanpage-nextcloud
    ports:
      - "8081:80"
    restart: unless-stopped

  odoo:
    build: ./odoo
    container_name: fanpage-odoo
    ports:
      - "8082:80"
    restart: unless-stopped

  odoo-restaurante:
    build: ./odoo-restaurante
    container_name: fanpage-odoo-restaurante
    ports:
      - "8083:80"
    restart: unless-stopped

  digiturno:
    build: ./digiturno
    container_name: fanpage-digiturno
    ports:
      - "8084:80"
    restart: unless-stopped

  master:
    build: ./master
    container_name: fanpage-master
    ports:
      - "80:80"
    restart: unless-stopped
